
# Add Repository
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

cask_args appdir: "/Applications"

#==================
# brew
#==================
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'tmux'
brew 'vim'
brew 'git'
brew 'gist'
brew 'gibo'
brew 'hub'
brew 'tig'
brew 'tree'
brew 'wget'
brew 'curl'
brew 'jq'
brew 'scala'
brew 'gradle'
brew 'sbt'
brew 'atool'
brew 'z'
brew 'fontforge'
brew 'peco'
brew 'zplug'
brew 'starship'
brew 'font-hackgen'
brew 'font-hackgen-nerd'

#==================
# cask
#==================
cask 'alfred'
cask 'appcleaner'
cask 'cmd-eikana'
cask 'docker'
cask 'bettertouchtool'
cask 'google-japanese-ime'
cask 'karabiner-elements'
cask 'kindle'
cask 'iterm2'
cask 'quiver'
cask 'skitch'
cask 'sourcetree'
cask 'sequel-pro'
cask 'the-unarchiver'
cask 'visual-studio-code'