# Update Homebrew
#update

# Update already-installed formula
# upgrade

# Add Repository
tap "homebrew/cask"
tap "homebrew/cask-fonts"

#==================
# Packages
#==================
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'tmux'
brew 'vim'
brew 'git'
# https://github.com/defunkt/gist/
brew 'gist'
# https://github.com/simonwhitaker/gibo
brew 'gibo'
# https://github.com/github/hub
brew 'hub'
brew 'tig'
brew 'tree'
brew 'wget'
brew 'curl'
# https://github.com/stedolan/jq
brew 'jq'
brew 'scala'
brew 'gradle'
brew 'sbt'
brew 'atool'
brew 'z'
brew 'fontforge'
brew 'peco'
brew 'zplug'
brew 'starship'

# powerline用フォントを作成する
tap 'sanemat/font'
brew '--powerline --vim-powerline ricty'
brew '--with-powerline ricty'

# hakugen
brew 'font-hackgen'
brew 'font-hackgen-nerd'

#==================
# .dmg
#==================
cask 'alfred'
cask 'appcleaner'
cask 'cmd-eikana'
cask 'docker'
cask 'bettertouchtool'
# cask 'flux'
cask 'google-japanese-ime'
# cask ' intellij-idea-community
cask 'karabiner-elements'
cask 'kindle'
cask 'iterm2'
cask 'quiver'
cask 'skitch'
cask 'sourcetree'
cask 'sequel-pro'
cask 'the-unarchiver'
cask 'visual-studio-code'

# Remove outdated versions
#cleanup
